### ISSUE TITLE
[ 배포 ] Frontend Deploy document

### ISSUE THREAD

**Issue by parc02** [Team5-be01-Final-Project/Frontend#32]
### EC2 INSTANCE 생성
- https://github.com/Team5-be01-Final-Project/.github/issues/28
### BUCKET, CODEDEPLOY
- https://github.com/beyond-sw-camp/beyond-sw-camp-be01_last-dance/issues/102

**Comment by parc02** [comment]
## STEP 2

**Comment by parc02** [comment]
## STEP GitHub Repository Secrets 액세스 키 저장(각자)
- 위 TL로 부터 전달 받은 CSV 참조(WSL 에서 CAT 으로 열어 확인)
- Github Repository → Settings → Secrets and variables → Actions → New repository secret
- AWS_ACCESS_KEY_ID 생성
- AWS_SECRET_ACCESS_KEY 생성
![image](https://github.com/Team5-be01-Final-Project/Frontend2/assets/148880521/4c2ea6df-b762-4916-9b84-13b56c72cb8d)

**Comment by parc02** [comment]
## AWS EC2 내부 설정
- aws cli 설치
```
# ec2 접속
$ mkdir tmp
$ cd tmp
$ curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
$ unzip awscliv2.zip
$ sudo ./aws/install

# 각 리전 참조 : https://docs.aws.amazon.com/ko_kr/AWSEC2/latest/UserGuide/using-regions-availability-zones.html
$ sudo aws configure
AWS Access Key ID [None]: <CSV - AWS_ACCESS_KEY_ID 입력>
AWS Secret Access Key [None]: <CSV-AWS_SECRET_ACCESS_KEY>
Default region name [None]: 
Default output format [None]: json
```

- codedeploy-agent 설치
```
# 루비 설치
$ sudo apt update
$ sudo apt install ruby-full
$ sudo apt install wget

$ wget https://aws-codedeploy-ap-northeast-2.s3.ap-northeast-2.amazonaws.com/latest/install
$ chmod +x ./install
$ sudo ./install auto > /tmp/logfile

# 실행 확인
$ sudo service codedeploy-agent status

# 인스턴스가 부팅시 codedeploy-agent 가 자동 실행 파일 작성 및 권한
$ sudo cat /etc/init.d/codedeploy-startup.sh
#!/bin
sudo service codedeploy-agent restart
$ sudo chmod +x /etc/init.d/codedeploy-startup.sh

```

**Comment by parc02** [comment]
- https://velog.io/@cataiden/ci-cd-with-github-actions-and-aws-codedeploy
- https://ymkmoon.github.io/Aws-12-Cicd/
- [이거 확인해봐](https://velog.io/@zlemzlem5656/Vue-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-Github-Action-Docker-%EC%9D%B4%EC%9A%A9%ED%95%B4%EC%84%9C-EC2%EC%97%90-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0)


-https://mag1c.tistory.com/465

**Comment by parc02** [comment]
## .github/workflows/actiondev.yml 생성
```
name: Deployaws

on:
  push:
    branches:
      - release/1.0.0
  pull_request:
    types:
      - closed

jobs:
  deploy:
#    if: github.event.pull_request.merged == true
    environment: release/1.0.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # AWS 인증 (IAM 사용자 Access Key, Secret Key 활용)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # 빌드 결과물을 S3 버킷에 업로드
      - name: Upload to AWS S3
        run: |
          aws deploy push \
            --application-name ${{ vars.CODE_DEPLOY_APP_NAME }} \
            --ignore-hidden-files \
            --s3-location s3://${{ vars.S3_BUCKET_NAME }}/$GITHUB_SHA.zip \
            --source .

      # S3 버킷에 있는 파일을 대상으로 CodeDeploy 실행
      - name: Deploy to AWS EC2 from S3
        run: |
          aws deploy create-deployment \
            --application-name ${{ vars.CODE_DEPLOY_APP_NAME }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name ${{ vars.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
            --s3-location bucket=${{ vars.S3_BUCKET_NAME }},key=$GITHUB_SHA.zip,bundleType=zip
```

## appspec.yml 생성
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/bps
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: start.sh
      timeout: 300
      runas: ubuntu
```
 ## aws deploy 확인
![image](https://github.com/Team5-be01-Final-Project/Frontend2/assets/148880521/fe111dba-6083-4389-a41a-19c5d3069df2)

**Comment by parc02** [comment]
## EC2 내부에 nvm npm 설치 및 버전 변경
- nvm 설치 
```
$ nvm install 14.4.0
```
- node.js 설치
```
$ sudo apt install nodejs
$ node install 20.11.0
```
- npm 버전 변경
```
$ npm install -g npm@10.5.0
```

**Comment by parc02** [comment]
## (BUG) EC2내부에서 localhost가 띄어졌지만 해당 ip:port로 접근이 불가능합니다.

- 문제상황 : EC2내부에서 curl 명령어로 화면이 띄어지는건 확인했지만 ec2ip:port로는 접근이 불가능 합니다

<<해결방법>>
```
만약에 localhost 가 아닌 외부 서버에서 dev-server 실행 시, –host 옵션을 추가하지 않으면 접근이 안됩니다.
 localhost 인경우에는 생략하시면 됩니다. 
-https://meongae.tistory.com/37
```
- 위의 방법에 따라 npm 에서 host할때 0.0.0.0으로 해주니 접근 가능합니다.
- npm에서 host를 옵션을 0.0.0.0을 주는 방법은 아래의 package.json에서 다음과 같이 수정해주시면 됩니다/
```
{
  "name": "vuestic-app",
  "version": "0.1.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --host 0.0.0.0",   <--------  해당부분
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "axios": "^1.6.8",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0",
    "vuestic-ui": "^1.9.0"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.0.4",
    "vite": "^5.1.6"
  }
}
```

**Comment by parc02** [comment]
## FrontEnd Docker로 배포하기
EC2 내부에 docker, dockercompose 다운받기
```
sudo apt update
$ sudo apt install docker
$ docker -v
$ sudo service docker start
$  sudo usermod -aG docker ubuntu
$ sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
$ sudo chmod +x /usr/local/bin/docker-compose
$ docker-compose --version
```
- Dockerfile
```
FROM node:20.11.0
WORKDIR /app
COPY . .
RUN npm install
CMD ["npm", "run", "dev"]
```

- docker-compose.yml
```
version: '3'
services:
  app:  # 'app'은 서비스 이름으로, 원하는 대로 변경할 수 있습니다.
    build: .  # 현재 디렉토리의 Dockerfile을 사용하여 이미지를 빌드합니다.
    ports:
      - "5173:5173"
    command: npm run dev  # 컨테이너가 시작될 때 실행될 커맨드를 정의합니다.
    volumes:
      - .:/app  # 현재 디렉토리를 컨테이너의 /app 디렉토리에 마운트합니다.
      - /app/node_modules  # node_modules 디렉토리를 마운트하여 오버라이드 방지
    environment:
      - NODE_ENV=development  # 필요한 환경 변수를 설정할 수 있습니다.

```
- start.sh
```
#!/usr/bin/env bash

cd /home/ubuntu/app/bps
# Docker Compose를 사용하여 컨테이너를 시작합니다.
docker-compose -f docker-compose.yml up -d
```
- stop.sh
```
#!/usr/bin/env bash

echo "stop"
ls
```
